run:
  timeout: 10m
  allow-parallel-runners: true

  build-tags:
    - e2e
    - performance
    - probe
    - preupgrade
    - postupgrade
    - postdowngrade

  exclude-dirs:
    - pkg/client

  exclude-files:
    - ".pb.go$"

output:
  uniq-by-line: true
  sort-results: true
  sort-order:
  - linter
  - file
  show-stats: true

linters:
  enable:
    - asciicheck
    - errorlint
    - gosec
    - prealloc
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unparam
  disable:
    - errcheck

linters-settings:
  revive:
    rules:
    # use unparam linter instead - defaults are better
    - name: unused-parameter
      disabled: true

issues:
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec
        - unparam
        - noctx
        - dot-imports

    # Allow source and sink receivers in conversion code for clarity.
    - path: _conversion\.go
      text: "ST1016:"
      linters:
        - stylecheck
