#! Used when internal-encryption is set to "true"
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: knative-serving-certs
  namespace: knative-serving
  labels:
    networking.knative.dev/ingress-provider: contour
    app.kubernetes.io/component: net-contour
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: devel
spec:
  delegations:
    - secretName: knative-serving-certs
      targetNamespaces:
      - "*"
