/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by injection-gen. DO NOT EDIT.

package client

import (
	context "context"
	json "encoding/json"
	errors "errors"
	fmt "fmt"

	v1 "github.com/projectcontour/contour/apis/projectcontour/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	discovery "k8s.io/client-go/discovery"
	dynamic "k8s.io/client-go/dynamic"
	rest "k8s.io/client-go/rest"
	versioned "knative.dev/net-contour/pkg/client/clientset/versioned"
	typedprojectcontourv1 "knative.dev/net-contour/pkg/client/clientset/versioned/typed/projectcontour/v1"
	injection "knative.dev/pkg/injection"
	dynamicclient "knative.dev/pkg/injection/clients/dynamicclient"
	logging "knative.dev/pkg/logging"
)

func init() {
	injection.Default.RegisterClient(withClientFromConfig)
	injection.Default.RegisterClientFetcher(func(ctx context.Context) interface{} {
		return Get(ctx)
	})
	injection.Dynamic.RegisterDynamicClient(withClientFromDynamic)
}

// Key is used as the key for associating information with a context.Context.
type Key struct{}

func withClientFromConfig(ctx context.Context, cfg *rest.Config) context.Context {
	return context.WithValue(ctx, Key{}, versioned.NewForConfigOrDie(cfg))
}

func withClientFromDynamic(ctx context.Context) context.Context {
	return context.WithValue(ctx, Key{}, &wrapClient{dyn: dynamicclient.Get(ctx)})
}

// Get extracts the versioned.Interface client from the context.
func Get(ctx context.Context) versioned.Interface {
	untyped := ctx.Value(Key{})
	if untyped == nil {
		if injection.GetConfig(ctx) == nil {
			logging.FromContext(ctx).Panic(
				"Unable to fetch knative.dev/net-contour/pkg/client/clientset/versioned.Interface from context. This context is not the application context (which is typically given to constructors via sharedmain).")
		} else {
			logging.FromContext(ctx).Panic(
				"Unable to fetch knative.dev/net-contour/pkg/client/clientset/versioned.Interface from context.")
		}
	}
	return untyped.(versioned.Interface)
}

type wrapClient struct {
	dyn dynamic.Interface
}

var _ versioned.Interface = (*wrapClient)(nil)

func (w *wrapClient) Discovery() discovery.DiscoveryInterface {
	panic("Discovery called on dynamic client!")
}

func convert(from interface{}, to runtime.Object) error {
	bs, err := json.Marshal(from)
	if err != nil {
		return fmt.Errorf("Marshal() = %w", err)
	}
	if err := json.Unmarshal(bs, to); err != nil {
		return fmt.Errorf("Unmarshal() = %w", err)
	}
	return nil
}

// ProjectcontourV1 retrieves the ProjectcontourV1Client
func (w *wrapClient) ProjectcontourV1() typedprojectcontourv1.ProjectcontourV1Interface {
	return &wrapProjectcontourV1{
		dyn: w.dyn,
	}
}

type wrapProjectcontourV1 struct {
	dyn dynamic.Interface
}

func (w *wrapProjectcontourV1) RESTClient() rest.Interface {
	panic("RESTClient called on dynamic client!")
}

func (w *wrapProjectcontourV1) HTTPProxies(namespace string) typedprojectcontourv1.HTTPProxyInterface {
	return &wrapProjectcontourV1HTTPProxyImpl{
		dyn: w.dyn.Resource(schema.GroupVersionResource{
			Group:    "projectcontour.io",
			Version:  "v1",
			Resource: "httpproxies",
		}),

		namespace: namespace,
	}
}

type wrapProjectcontourV1HTTPProxyImpl struct {
	dyn dynamic.NamespaceableResourceInterface

	namespace string
}

var _ typedprojectcontourv1.HTTPProxyInterface = (*wrapProjectcontourV1HTTPProxyImpl)(nil)

func (w *wrapProjectcontourV1HTTPProxyImpl) Create(ctx context.Context, in *v1.HTTPProxy, opts metav1.CreateOptions) (*v1.HTTPProxy, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "projectcontour.io",
		Version: "v1",
		Kind:    "HTTPProxy",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Create(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.HTTPProxy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1HTTPProxyImpl) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return w.dyn.Namespace(w.namespace).Delete(ctx, name, opts)
}

func (w *wrapProjectcontourV1HTTPProxyImpl) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	return w.dyn.Namespace(w.namespace).DeleteCollection(ctx, opts, listOpts)
}

func (w *wrapProjectcontourV1HTTPProxyImpl) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.HTTPProxy, error) {
	uo, err := w.dyn.Namespace(w.namespace).Get(ctx, name, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.HTTPProxy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1HTTPProxyImpl) List(ctx context.Context, opts metav1.ListOptions) (*v1.HTTPProxyList, error) {
	uo, err := w.dyn.Namespace(w.namespace).List(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.HTTPProxyList{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1HTTPProxyImpl) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.HTTPProxy, err error) {
	uo, err := w.dyn.Namespace(w.namespace).Patch(ctx, name, pt, data, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.HTTPProxy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1HTTPProxyImpl) Update(ctx context.Context, in *v1.HTTPProxy, opts metav1.UpdateOptions) (*v1.HTTPProxy, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "projectcontour.io",
		Version: "v1",
		Kind:    "HTTPProxy",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Update(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.HTTPProxy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1HTTPProxyImpl) UpdateStatus(ctx context.Context, in *v1.HTTPProxy, opts metav1.UpdateOptions) (*v1.HTTPProxy, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "projectcontour.io",
		Version: "v1",
		Kind:    "HTTPProxy",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).UpdateStatus(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.HTTPProxy{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1HTTPProxyImpl) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return nil, errors.New("NYI: Watch")
}

func (w *wrapProjectcontourV1) TLSCertificateDelegations(namespace string) typedprojectcontourv1.TLSCertificateDelegationInterface {
	return &wrapProjectcontourV1TLSCertificateDelegationImpl{
		dyn: w.dyn.Resource(schema.GroupVersionResource{
			Group:    "projectcontour.io",
			Version:  "v1",
			Resource: "tlscertificatedelegations",
		}),

		namespace: namespace,
	}
}

type wrapProjectcontourV1TLSCertificateDelegationImpl struct {
	dyn dynamic.NamespaceableResourceInterface

	namespace string
}

var _ typedprojectcontourv1.TLSCertificateDelegationInterface = (*wrapProjectcontourV1TLSCertificateDelegationImpl)(nil)

func (w *wrapProjectcontourV1TLSCertificateDelegationImpl) Create(ctx context.Context, in *v1.TLSCertificateDelegation, opts metav1.CreateOptions) (*v1.TLSCertificateDelegation, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "projectcontour.io",
		Version: "v1",
		Kind:    "TLSCertificateDelegation",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Create(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.TLSCertificateDelegation{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1TLSCertificateDelegationImpl) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return w.dyn.Namespace(w.namespace).Delete(ctx, name, opts)
}

func (w *wrapProjectcontourV1TLSCertificateDelegationImpl) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	return w.dyn.Namespace(w.namespace).DeleteCollection(ctx, opts, listOpts)
}

func (w *wrapProjectcontourV1TLSCertificateDelegationImpl) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.TLSCertificateDelegation, error) {
	uo, err := w.dyn.Namespace(w.namespace).Get(ctx, name, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.TLSCertificateDelegation{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1TLSCertificateDelegationImpl) List(ctx context.Context, opts metav1.ListOptions) (*v1.TLSCertificateDelegationList, error) {
	uo, err := w.dyn.Namespace(w.namespace).List(ctx, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.TLSCertificateDelegationList{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1TLSCertificateDelegationImpl) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.TLSCertificateDelegation, err error) {
	uo, err := w.dyn.Namespace(w.namespace).Patch(ctx, name, pt, data, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.TLSCertificateDelegation{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1TLSCertificateDelegationImpl) Update(ctx context.Context, in *v1.TLSCertificateDelegation, opts metav1.UpdateOptions) (*v1.TLSCertificateDelegation, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "projectcontour.io",
		Version: "v1",
		Kind:    "TLSCertificateDelegation",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).Update(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.TLSCertificateDelegation{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1TLSCertificateDelegationImpl) UpdateStatus(ctx context.Context, in *v1.TLSCertificateDelegation, opts metav1.UpdateOptions) (*v1.TLSCertificateDelegation, error) {
	in.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "projectcontour.io",
		Version: "v1",
		Kind:    "TLSCertificateDelegation",
	})
	uo := &unstructured.Unstructured{}
	if err := convert(in, uo); err != nil {
		return nil, err
	}
	uo, err := w.dyn.Namespace(w.namespace).UpdateStatus(ctx, uo, opts)
	if err != nil {
		return nil, err
	}
	out := &v1.TLSCertificateDelegation{}
	if err := convert(uo, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (w *wrapProjectcontourV1TLSCertificateDelegationImpl) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return nil, errors.New("NYI: Watch")
}
