#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all,expects=17
#@overlay/match-child-defaults missing_ok=True
---
metadata:
  labels:
    networking.knative.dev/ingress-provider: contour
