#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ if data.values.namespace == "contour-internal":
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-contour-internal
  labels:
    networking.knative.dev/ingress-provider: contour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  #@yaml/text-templated-strings
  name: (@= data.values.clusterrole.name @)
subjects:
- kind: ServiceAccount
  name: contour
  namespace: contour-internal

#@ end

#@ if data.values.namespace == "contour-external":
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-contour-external
  labels:
    networking.knative.dev/ingress-provider: contour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  #@yaml/text-templated-strings
  name: (@= data.values.clusterrole.name @)
subjects:
- kind: ServiceAccount
  name: contour
  namespace: contour-external

#@ end