#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  #@yaml/text-templated-strings
  name: "knative-(@= data.values.namespace @)"
  labels:
    networking.knative.dev/ingress-provider: contour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ data.values.clusterrole.name
subjects:
- kind: ServiceAccount
  name: contour
  namespace: #@ data.values.namespace