apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: contour-operator
  name: contour-external
---
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-external
  namespace: contour-external
spec:
  namespace:
    name: contour-external
  ingressClassName: contour-external
