/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/projectcontour/contour/apis/projectcontour/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTLSCertificateDelegations implements TLSCertificateDelegationInterface
type FakeTLSCertificateDelegations struct {
	Fake *FakeProjectcontourV1
	ns   string
}

var tlscertificatedelegationsResource = v1.SchemeGroupVersion.WithResource("tlscertificatedelegations")

var tlscertificatedelegationsKind = v1.SchemeGroupVersion.WithKind("TLSCertificateDelegation")

// Get takes name of the tLSCertificateDelegation, and returns the corresponding tLSCertificateDelegation object, and an error if there is any.
func (c *FakeTLSCertificateDelegations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.TLSCertificateDelegation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tlscertificatedelegationsResource, c.ns, name), &v1.TLSCertificateDelegation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TLSCertificateDelegation), err
}

// List takes label and field selectors, and returns the list of TLSCertificateDelegations that match those selectors.
func (c *FakeTLSCertificateDelegations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.TLSCertificateDelegationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tlscertificatedelegationsResource, tlscertificatedelegationsKind, c.ns, opts), &v1.TLSCertificateDelegationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.TLSCertificateDelegationList{ListMeta: obj.(*v1.TLSCertificateDelegationList).ListMeta}
	for _, item := range obj.(*v1.TLSCertificateDelegationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tLSCertificateDelegations.
func (c *FakeTLSCertificateDelegations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tlscertificatedelegationsResource, c.ns, opts))

}

// Create takes the representation of a tLSCertificateDelegation and creates it.  Returns the server's representation of the tLSCertificateDelegation, and an error, if there is any.
func (c *FakeTLSCertificateDelegations) Create(ctx context.Context, tLSCertificateDelegation *v1.TLSCertificateDelegation, opts metav1.CreateOptions) (result *v1.TLSCertificateDelegation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tlscertificatedelegationsResource, c.ns, tLSCertificateDelegation), &v1.TLSCertificateDelegation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TLSCertificateDelegation), err
}

// Update takes the representation of a tLSCertificateDelegation and updates it. Returns the server's representation of the tLSCertificateDelegation, and an error, if there is any.
func (c *FakeTLSCertificateDelegations) Update(ctx context.Context, tLSCertificateDelegation *v1.TLSCertificateDelegation, opts metav1.UpdateOptions) (result *v1.TLSCertificateDelegation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tlscertificatedelegationsResource, c.ns, tLSCertificateDelegation), &v1.TLSCertificateDelegation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TLSCertificateDelegation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTLSCertificateDelegations) UpdateStatus(ctx context.Context, tLSCertificateDelegation *v1.TLSCertificateDelegation, opts metav1.UpdateOptions) (*v1.TLSCertificateDelegation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tlscertificatedelegationsResource, "status", c.ns, tLSCertificateDelegation), &v1.TLSCertificateDelegation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TLSCertificateDelegation), err
}

// Delete takes name of the tLSCertificateDelegation and deletes it. Returns an error if one occurs.
func (c *FakeTLSCertificateDelegations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(tlscertificatedelegationsResource, c.ns, name, opts), &v1.TLSCertificateDelegation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTLSCertificateDelegations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tlscertificatedelegationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.TLSCertificateDelegationList{})
	return err
}

// Patch applies the patch and returns the patched tLSCertificateDelegation.
func (c *FakeTLSCertificateDelegations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.TLSCertificateDelegation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tlscertificatedelegationsResource, c.ns, name, pt, data, subresources...), &v1.TLSCertificateDelegation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TLSCertificateDelegation), err
}
